### ISSUE TITLE
Why would the CrashPlan backup not exist?

### ISSUE THREAD

**Issue by tamarw** [jedda/OSX-Monitoring-Tools#11]
Hi, not on OS X but I don't think that'd make a difference. I'm experiencing the issue below:

.# locate cp.properties
/usr/local/crashplan/cache/42/cp.properties
.# ./check_crashplan.sh
CRITICAL - the CrashPlan backup you pointed to does not exist! - /usr/local/crashplan/

I also tried /usr/local/crashplan/cache and /usr/local/crashplan/cache/42/ but both failed. 

But it's there, is it not?

**Comment by jordantrizz** [comment]
I'm not using OSX either and was able to get this working. Does nagios/nrpe not have permissions to this folder?

**Comment by tamarw** [comment]
Does it need r/w perms? I have 755 (root is owner).

**Comment by jordantrizz** [comment]
I modified this script to work with CrashPlan pro.

https://github.com/jordantrizz/nagios-additional-plugins/blob/master/check_crashplan_pro

**Comment by tamarw** [comment]
Thanks Jordan - still doesn't work though.

.# cd /usr/local/crashplan
.# ls
bin    conf                 ~custom  install.vars  lang  libjniwrap64.so  libjtux64.so  libmd564.so  log   upgrade
cache  CrashPlanEngine.pid  doc      jniwrap.lic   lib   libjniwrap.so    libjtux.so    libmd5.so    skin
.# /usr/lib64/nagios/plugins/check_crashplan_pro 
CRITICAL - the CrashPlan backup you pointed to does not exist! - /usr/local/crashplan

**Comment by tamarw** [comment]
Anyone?

**Comment by jordantrizz** [comment]
Shoot me an email (on my profile) and we can try to link up and test things!
